name: screen_orientation
description: '实时监测Android/IOS屏幕方向的插件'
version: 0.0.1

environment:
  sdk: '>=3.0.0-35.0.dev <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cn.screen_orientation
        pluginClass: ScreenOrientationPlugin
      ios:
        pluginClass: ScreenOrientationPlugin